### ISSUE TITLE
Feature: Enable Dependabot Version Updates

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/denverdevs.org#154]
We can enable Dependabot Version Updates, but it requires a bit of setup. I figured I'd open this up to anyone who might want to go tinker with it. What I would need is the dependabot.yml file that we'd drop in, here's what Github gives us: 

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

```
